# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='doc',
        ),
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Kategori'),
            preserve_default=False,
        ),
    ]
