# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_auto_20171113_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
